/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Admins {
  name: string | null;
  password: string;
  password_name: string | null;
  role_id: string | null;
  username: string;
  uuid: Generated<string>;
}

export interface Roles {
  name: string;
  uuid: Generated<string>;
}

export interface DB {
  admins: Admins;
  roles: Roles;
}
